// Generated from the source of https://docs.fivem.net/docs/game-references/blips/
// June 2020
// Commented out special, invalid and duplicate blips
function spriteList() {
    return [
        // [0, "blips/radar_higher.png", "radar_higher"],
        [1, "blips/radar_level.png", "radar_level"],
        // [2, "blips/radar_lower.png", "radar_lower"],
        [3, "blips/radar_police_ped.png", "radar_police_ped"],
        [4, "blips/radar_wanted_radius.png", "radar_wanted_radius"],
        // [5, "blips/radar_area_blip.png", "radar_area_blip"],
        // [6, "blips/radar_centre.png", "radar_centre"],
        // [7, "blips/radar_north.png", "radar_north"],
        // [8, "blips/radar_waypoint.png", "radar_waypoint"],
        // [9, "blips/radar_radius_blip.png", "radar_radius_blip"],
        // [10, "blips/radar_radius_outline_blip.png", "radar_radius_outline_blip"],
        [11, "blips/radar_weapon_higher.png", "radar_weapon_higher"],
        [12, "blips/radar_weapon_lower.png", "radar_weapon_lower"],
        [13, "blips/radar_higher_ai.png", "radar_higher_ai"],
        [14, "blips/radar_lower_ai.png", "radar_lower_ai"],
        [15, "blips/radar_police_heli_spin.png", "radar_police_heli_spin"],
        [16, "blips/radar_police_plane_move.png", "radar_police_plane_move"],
        // [27, "blips/radar_mp_crew.png", "radar_mp_crew"],
        // [28, "blips/radar_mp_friendlies.png", "radar_mp_friendlies"],
        [36, "blips/radar_cable_car.png", "radar_cable_car"],
        // [37, "blips/radar_activities.png", "radar_activities"],
        [38, "blips/radar_raceflag.png", "radar_raceflag"],
        [40, "blips/radar_safehouse.png", "radar_safehouse"],
        [41, "blips/radar_police.png", "radar_police"],
        [42, "blips/radar_police_chase.png", "radar_police_chase"],
        [43, "blips/radar_police_heli.png", "radar_police_heli"],
        // [44, "blips/radar_bomb_a.png", "radar_bomb_a"],
        [47, "blips/radar_snitch.png", "radar_snitch"],
        // [48, "blips/radar_planning_locations.png", "radar_planning_locations"],
        [50, "blips/radar_crim_carsteal.png", "radar_crim_carsteal"],
        [51, "blips/radar_crim_drugs.png", "radar_crim_drugs"],
        [52, "blips/radar_crim_holdups.png", "radar_crim_holdups"],
        // [54, "blips/radar_crim_player.png", "radar_crim_player"],
        [56, "blips/radar_cop_patrol.png", "radar_cop_patrol"],
        [57, "blips/radar_cop_player.png", "radar_cop_player"],
        [58, "blips/radar_crim_wanted.png", "radar_crim_wanted"],
        [59, "blips/radar_heist.png", "radar_heist"],
        [60, "blips/radar_police_station.png", "radar_police_station"],
        [61, "blips/radar_hospital.png", "radar_hospital"],
        // [62, "blips/radar_assassins_mark.png", "radar_assassins_mark"],
        // [63, "blips/radar_elevator.png", "radar_elevator"],
        [64, "blips/radar_helicopter.png", "radar_helicopter"],
        [66, "blips/radar_random_character.png", "radar_random_character"],
        [67, "blips/radar_security_van.png", "radar_security_van"],
        [68, "blips/radar_tow_truck.png", "radar_tow_truck"],
        // [70, "blips/radar_illegal_parking.png", "radar_illegal_parking"],
        [71, "blips/radar_barber.png", "radar_barber"],
        [72, "blips/radar_car_mod_shop.png", "radar_car_mod_shop"],
        [73, "blips/radar_clothes_store.png", "radar_clothes_store"],
        [75, "blips/radar_tattoo.png", "radar_tattoo"],
        // Letters
        [76, "blips/radar_armenian_family.png", "radar_armenian_family"],
        [106, "blips/radar_fbi_officers_strand.png", "radar_fbi_officers_strand"],
        [89, "blips/radar_chinese_strand.png", "radar_chinese_strand"],
        [86, "blips/radar_lamar_family.png", "radar_lamar_family"],
        [80, "blips/radar_jewelry_heist.png", "radar_jewelry_heist"],
        [77, "blips/radar_lester_family.png", "radar_lester_family"],
        [78, "blips/radar_michael_family.png", "radar_michael_family"],
        [267, "blips/radar_property.png", "radar_property"],
        [120, "blips/radar_solomon_strand.png", "radar_solomon_strand"],
        [79, "blips/radar_trevor_family.png", "radar_trevor_family"],
        [112, "blips/radar_michael_family_exile.png", "radar_michael_family_exile"],
        // [82, "blips/radar_drag_race_finish.png", "radar_drag_race_finish"],
        [84, "blips/radar_rampage.png", "radar_rampage"],
        [85, "blips/radar_vinewood_tours.png", "radar_vinewood_tours"],
        // [88, "blips/radar_franklin_family.png", "radar_franklin_family"],
        [90, "blips/radar_flight_school.png", "radar_flight_school"],
        // [91, "blips/radar_eye_sky.png", "radar_eye_sky"],
        // [92, "blips/radar_air_hockey.png", "radar_air_hockey"],
        [93, "blips/radar_bar.png", "radar_bar"],
        [94, "blips/radar_base_jump.png", "radar_base_jump"],
        // [95, "blips/radar_basketball.png", "radar_basketball"],
        // [96, "blips/radar_biolab_heist.png", "radar_biolab_heist"],
        // [99, "blips/radar_cabaret_club.png", "radar_cabaret_club"],
        [100, "blips/radar_car_wash.png", "radar_car_wash"],
        [102, "blips/radar_comedy_club.png", "radar_comedy_club"],
        [103, "blips/radar_darts.png", "radar_darts"],
        // [104, "blips/radar_docks_heist.png", "radar_docks_heist"],
        // [105, "blips/radar_fbi_heist.png", "radar_fbi_heist"],
        // [107, "blips/radar_finale_bank_heist.png", "radar_finale_bank_heist"],
        [108, "blips/radar_financier_strand.png", "radar_financier_strand"],
        [109, "blips/radar_golf.png", "radar_golf"],
        [110, "blips/radar_gun_shop.png", "radar_gun_shop"],
        // [111, "blips/radar_internet_cafe.png", "radar_internet_cafe"],
        // [113, "blips/radar_nice_house_heist.png", "radar_nice_house_heist"],
        // [114, "blips/radar_random_female.png", "radar_random_female"],
        // [115, "blips/radar_random_male.png", "radar_random_male"],
        // [118, "blips/radar_rural_bank_heist.png", "radar_rural_bank_heist"],
        [119, "blips/radar_shooting_range.png", "radar_shooting_range"],
        [121, "blips/radar_strip_club.png", "radar_strip_club"],
        [122, "blips/radar_tennis.png", "radar_tennis"],
        // [123, "blips/radar_trevor_family_exile.png", "radar_trevor_family_exile"],
        // [124, "blips/radar_michael_trevor_family.png", "radar_michael_trevor_family"],
        [126, "blips/radar_triathlon.png", "radar_triathlon"],
        [127, "blips/radar_off_road_racing.png", "radar_off_road_racing"],
        [128, "blips/radar_gang_cops.png", "radar_gang_cops"],
        // [129, "blips/radar_gang_mexicans.png", "radar_gang_mexicans"],
        // [130, "blips/radar_gang_bikers.png", "radar_gang_bikers"],
        [133, "blips/radar_snitch_red.png", "radar_snitch_red"],
        [134, "blips/radar_crim_cuff_keys.png", "radar_crim_cuff_keys"],
        [135, "blips/radar_cinema.png", "radar_cinema"],
        [136, "blips/radar_music_venue.png", "radar_music_venue"],
        [137, "blips/radar_police_station_blue.png", "radar_police_station_blue"],
        // [138, "blips/radar_airport.png", "radar_airport"],
        // [139, "blips/radar_crim_saved_vehicle.png", "radar_crim_saved_vehicle"],
        [140, "blips/radar_weed_stash.png", "radar_weed_stash"],
        [141, "blips/radar_hunting.png", "radar_hunting"],
        // [142, "blips/radar_pool.png", "radar_pool"],
        // [143, "blips/radar_objective_blue.png", "radar_objective_blue"],
        // [144, "blips/radar_objective_green.png", "radar_objective_green"],
        // [145, "blips/radar_objective_red.png", "radar_objective_red"],
        // [146, "blips/radar_objective_yellow.png", "radar_objective_yellow"],
        [147, "blips/radar_arms_dealing.png", "radar_arms_dealing"],
        // [148, "blips/radar_mp_friend.png", "radar_mp_friend"],
        [149, "blips/radar_celebrity_theft.png", "radar_celebrity_theft"],
        [150, "blips/radar_weapon_assault_rifle.png", "radar_weapon_assault_rifle"],
        [151, "blips/radar_weapon_bat.png", "radar_weapon_bat"],
        [152, "blips/radar_weapon_grenade.png", "radar_weapon_grenade"],
        [153, "blips/radar_weapon_health.png", "radar_weapon_health"],
        [154, "blips/radar_weapon_knife.png", "radar_weapon_knife"],
        [155, "blips/radar_weapon_molotov.png", "radar_weapon_molotov"],
        [156, "blips/radar_weapon_pistol.png", "radar_weapon_pistol"],
        [157, "blips/radar_weapon_rocket.png", "radar_weapon_rocket"],
        [158, "blips/radar_weapon_shotgun.png", "radar_weapon_shotgun"],
        [159, "blips/radar_weapon_smg.png", "radar_weapon_smg"],
        [160, "blips/radar_weapon_sniper.png", "radar_weapon_sniper"],
        [161, "blips/radar_mp_noise.png", "radar_mp_noise"],
        // [162, "blips/radar_poi.png", "radar_poi"],
        [163, "blips/radar_passive.png", "radar_passive"],
        [164, "blips/radar_usingmenu.png", "radar_usingmenu"],
        [171, "blips/radar_gang_cops_partner.png", "radar_gang_cops_partner"],
        [173, "blips/radar_weapon_minigun.png", "radar_weapon_minigun"],
        [175, "blips/radar_weapon_armour.png", "radar_weapon_armour"],
        [176, "blips/radar_property_takeover.png", "radar_property_takeover"],
        // [177, "blips/radar_gang_mexicans_highlight.png", "radar_gang_mexicans_highlight"],
        // [178, "blips/radar_gang_bikers_highlight.png", "radar_gang_bikers_highlight"],
        // [179, "blips/radar_triathlon_cycling.png", "radar_triathlon_cycling"],
        // [180, "blips/radar_triathlon_swimming.png", "radar_triathlon_swimming"],
        [181, "blips/radar_property_takeover_bikers.png", "radar_property_takeover_bikers"],
        // [182, "blips/radar_property_takeover_cops.png", "radar_property_takeover_cops"],
        // [183, "blips/radar_property_takeover_vagos.png", "radar_property_takeover_vagos"],
        [184, "blips/radar_camera.png", "radar_camera"],
        // [185, "blips/radar_centre_red.png", "radar_centre_red"],
        [186, "blips/radar_handcuff_keys_bikers.png", "radar_handcuff_keys_bikers"],
        // [187, "blips/radar_handcuff_keys_vagos.png", "radar_handcuff_keys_vagos"],
        [188, "blips/radar_handcuffs_closed_bikers.png", "radar_handcuffs_closed_bikers"],
        // [189, "blips/radar_handcuffs_closed_vagos.png", "radar_handcuffs_closed_vagos"],
        // [192, "blips/radar_camera_badger.png", "radar_camera_badger"],
        // [193, "blips/radar_camera_facade.png", "radar_camera_facade"],
        // [194, "blips/radar_camera_ifruit.png", "radar_camera_ifruit"],
        [197, "blips/radar_yoga.png", "radar_yoga"],
        [198, "blips/radar_taxi.png", "radar_taxi"],
        [205, "blips/radar_shrink.png", "radar_shrink"],
        [206, "blips/radar_epsilon.png", "radar_epsilon"],
        [207, "blips/radar_financier_strand_grey.png", "radar_financier_strand_grey"],
        // [208, "blips/radar_trevor_family_grey.png", "radar_trevor_family_grey"],
        // [209, "blips/radar_trevor_family_red.png", "radar_trevor_family_red"],
        // [210, "blips/radar_franklin_family_grey.png", "radar_franklin_family_grey"],
        // [211, "blips/radar_franklin_family_blue.png", "radar_franklin_family_blue"],
        // [212, "blips/radar_franklin_a.png", "radar_franklin_a"],
        // [213, "blips/radar_franklin_b.png", "radar_franklin_b"],
        [214, "blips/radar_franklin_c.png", "radar_franklin_c"],
        [225, "blips/radar_gang_vehicle.png", "radar_gang_vehicle"],
        [226, "blips/radar_gang_vehicle_bikers.png", "radar_gang_vehicle_bikers"],
        // [227, "blips/radar_gang_vehicle_cops.png", "radar_gang_vehicle_cops"],
        // [228, "blips/radar_gang_vehicle_vagos.png", "radar_gang_vehicle_vagos"],
        [229, "blips/radar_guncar.png", "radar_guncar"],
        // [230, "blips/radar_driving_bikers.png", "radar_driving_bikers"],
        // [231, "blips/radar_driving_cops.png", "radar_driving_cops"],
        // [232, "blips/radar_driving_vagos.png", "radar_driving_vagos"],
        // [233, "blips/radar_gang_cops_highlight.png", "radar_gang_cops_highlight"],
        // [234, "blips/radar_shield_bikers.png", "radar_shield_bikers"],
        // [235, "blips/radar_shield_cops.png", "radar_shield_cops"],
        // [236, "blips/radar_shield_vagos.png", "radar_shield_vagos"],
        [237, "blips/radar_custody_bikers.png", "radar_custody_bikers"],
        // [238, "blips/radar_custody_vagos.png", "radar_custody_vagos"],
        [251, "blips/radar_arms_dealing_air.png", "radar_arms_dealing_air"],
        // [252, "blips/radar_playerstate_arrested.png", "radar_playerstate_arrested"],
        // [253, "blips/radar_playerstate_custody.png", "radar_playerstate_custody"],
        // [254, "blips/radar_playerstate_driving.png", "radar_playerstate_driving"],
        // [255, "blips/radar_playerstate_keyholder.png", "radar_playerstate_keyholder"],
        // [256, "blips/radar_playerstate_partner.png", "radar_playerstate_partner"],
        // [262, "blips/radar_ztype.png", "radar_ztype"],
        // [263, "blips/radar_stinger.png", "radar_stinger"],
        // [264, "blips/radar_packer.png", "radar_packer"],
        // [265, "blips/radar_monroe.png", "radar_monroe"],
        [266, "blips/radar_fairground.png", "radar_fairground"],
        // [268, "blips/radar_gang_highlight.png", "radar_gang_highlight"],
        [269, "blips/radar_altruist.png", "radar_altruist"],
        [270, "blips/radar_ai.png", "radar_ai"],
        [271, "blips/radar_on_mission.png", "radar_on_mission"],
        [272, "blips/radar_cash_pickup.png", "radar_cash_pickup"],
        [273, "blips/radar_chop.png", "radar_chop"],
        [274, "blips/radar_dead.png", "radar_dead"],
        // [275, "blips/radar_territory_locked.png", "radar_territory_locked"],
        [276, "blips/radar_cash_lost.png", "radar_cash_lost"],
        // [277, "blips/radar_cash_vagos.png", "radar_cash_vagos"],
        // [278, "blips/radar_cash_cops.png", "radar_cash_cops"],
        [279, "blips/radar_hooker.png", "radar_hooker"],
        [280, "blips/radar_friend.png", "radar_friend"],
        // [281, "blips/radar_mission_2to4.png", "radar_mission_2to4"],
        // [282, "blips/radar_mission_2to8.png", "radar_mission_2to8"],
        // [283, "blips/radar_mission_2to12.png", "radar_mission_2to12"],
        // [284, "blips/radar_mission_2to16.png", "radar_mission_2to16"],
        [285, "blips/radar_custody_dropoff.png", "radar_custody_dropoff"],
        // [286, "blips/radar_onmission_cops.png", "radar_onmission_cops"],
        // [287, "blips/radar_onmission_lost.png", "radar_onmission_lost"],
        // [288, "blips/radar_onmission_vagos.png", "radar_onmission_vagos"],
        [289, "blips/radar_crim_carsteal_cops.png", "radar_crim_carsteal_cops"],
        // [290, "blips/radar_crim_carsteal_bikers.png", "radar_crim_carsteal_bikers"],
        // [291, "blips/radar_crim_carsteal_vagos.png", "radar_crim_carsteal_vagos"],
        // [292, "blips/radar_band_strand.png", "radar_band_strand"],
        // [293, "blips/radar_simeon_family.png", "radar_simeon_family"],
        // [294, "blips/radar_mission_1.png", "radar_mission_1"],
        // [295, "blips/radar_mission_2.png", "radar_mission_2"],
        // [296, "blips/radar_friend_darts.png", "radar_friend_darts"],
        // [297, "blips/radar_friend_comedyclub.png", "radar_friend_comedyclub"],
        // [298, "blips/radar_friend_cinema.png", "radar_friend_cinema"],
        // [299, "blips/radar_friend_tennis.png", "radar_friend_tennis"],
        // [300, "blips/radar_friend_stripclub.png", "radar_friend_stripclub"],
        // [301, "blips/radar_friend_livemusic.png", "radar_friend_livemusic"],
        // [302, "blips/radar_friend_golf.png", "radar_friend_golf"],
        [303, "blips/radar_bounty_hit.png", "radar_bounty_hit"],
        [304, "blips/radar_ugc_mission.png", "radar_ugc_mission"],
        [305, "blips/radar_horde.png", "radar_horde"],
        [306, "blips/radar_cratedrop.png", "radar_cratedrop"],
        [307, "blips/radar_plane_drop.png", "radar_plane_drop"],
        [308, "blips/radar_sub.png", "radar_sub"],
        [309, "blips/radar_race.png", "radar_race"],
        [310, "blips/radar_deathmatch.png", "radar_deathmatch"],
        [311, "blips/radar_arm_wrestling.png", "radar_arm_wrestling"],
        // [312, "blips/radar_mission_1to2.png", "radar_mission_1to2"],
        [313, "blips/radar_shootingrange_gunshop.png", "radar_shootingrange_gunshop"],
        [314, "blips/radar_race_air.png", "radar_race_air"],
        [315, "blips/radar_race_land.png", "radar_race_land"],
        [316, "blips/radar_race_sea.png", "radar_race_sea"],
        [317, "blips/radar_tow.png", "radar_tow"],
        [318, "blips/radar_garbage.png", "radar_garbage"],
        // [319, "blips/radar_drill.png", "radar_drill"],
        // [320, "blips/radar_spikes.png", "radar_spikes"],
        // [321, "blips/radar_firetruck.png", "radar_firetruck"],
        // [322, "blips/radar_minigun2.png", "radar_minigun2"],
        // [323, "blips/radar_bugstar.png", "radar_bugstar"],
        // [324, "blips/radar_submarine.png", "radar_submarine"],
        // [325, "blips/radar_chinook.png", "radar_chinook"],
        [326, "blips/radar_getaway_car.png", "radar_getaway_car"],
        // [327, "blips/radar_mission_bikers_1.png", "radar_mission_bikers_1"],
        // [328, "blips/radar_mission_bikers_1to2.png", "radar_mission_bikers_1to2"],
        // [329, "blips/radar_mission_bikers_2.png", "radar_mission_bikers_2"],
        // [330, "blips/radar_mission_bikers_2to4.png", "radar_mission_bikers_2to4"],
        // [331, "blips/radar_mission_bikers_2to8.png", "radar_mission_bikers_2to8"],
        // [332, "blips/radar_mission_bikers_2to12.png", "radar_mission_bikers_2to12"],
        // [333, "blips/radar_mission_bikers_2to16.png", "radar_mission_bikers_2to16"],
        // [334, "blips/radar_mission_cops_1.png", "radar_mission_cops_1"],
        // [335, "blips/radar_mission_cops_1to2.png", "radar_mission_cops_1to2"],
        // [336, "blips/radar_mission_cops_2.png", "radar_mission_cops_2"],
        // [337, "blips/radar_mission_cops_2to4.png", "radar_mission_cops_2to4"],
        // [338, "blips/radar_mission_cops_2to8.png", "radar_mission_cops_2to8"],
        // [339, "blips/radar_mission_cops_2to12.png", "radar_mission_cops_2to12"],
        // [340, "blips/radar_mission_cops_2to16.png", "radar_mission_cops_2to16"],
        // [341, "blips/radar_mission_vagos_1.png", "radar_mission_vagos_1"],
        // [342, "blips/radar_mission_vagos_1to2.png", "radar_mission_vagos_1to2"],
        // [343, "blips/radar_mission_vagos_2.png", "radar_mission_vagos_2"],
        // [344, "blips/radar_mission_vagos_2to4.png", "radar_mission_vagos_2to4"],
        // [345, "blips/radar_mission_vagos_2to8.png", "radar_mission_vagos_2to8"],
        // [346, "blips/radar_mission_vagos_2to12.png", "radar_mission_vagos_2to12"],
        // [347, "blips/radar_mission_vagos_2to16.png", "radar_mission_vagos_2to16"],
        [348, "blips/radar_gang_bike.png", "radar_gang_bike"],
        // [349, "blips/radar_gas_grenade.png", "radar_gas_grenade"],
        [350, "blips/radar_property_for_sale.png", "radar_property_for_sale"],
        [351, "blips/radar_gang_attack_package.png", "radar_gang_attack_package"],
        [352, "blips/radar_martin_madrazzo.png", "radar_martin_madrazzo"],
        [353, "blips/radar_enemy_heli_spin.png", "radar_enemy_heli_spin"],
        [354, "blips/radar_boost.png", "radar_boost"],
        [355, "blips/radar_devin.png", "radar_devin"],
        [356, "blips/radar_dock.png", "radar_dock"],
        [357, "blips/radar_garage.png", "radar_garage"],
        [358, "blips/radar_golf_flag.png", "radar_golf_flag"],
        [359, "blips/radar_hangar.png", "radar_hangar"],
        [360, "blips/radar_helipad.png", "radar_helipad"],
        [361, "blips/radar_jerry_can.png", "radar_jerry_can"],
        [362, "blips/radar_mask.png", "radar_mask"],
        [363, "blips/radar_heist_prep.png", "radar_heist_prep"],
        [364, "blips/radar_incapacitated.png", "radar_incapacitated"],
        [365, "blips/radar_spawn_point_pickup.png", "radar_spawn_point_pickup"],
        [366, "blips/radar_boilersuit.png", "radar_boilersuit"],
        [367, "blips/radar_completed.png", "radar_completed"],
        [368, "blips/radar_rockets.png", "radar_rockets"],
        [369, "blips/radar_garage_for_sale.png", "radar_garage_for_sale"],
        [370, "blips/radar_helipad_for_sale.png", "radar_helipad_for_sale"],
        [371, "blips/radar_dock_for_sale.png", "radar_dock_for_sale"],
        [372, "blips/radar_hangar_for_sale.png", "radar_hangar_for_sale"],
        [373, "blips/radar_placeholder_6.png", "radar_placeholder_6"],
        [374, "blips/radar_business.png", "radar_business"],
        [375, "blips/radar_business_for_sale.png", "radar_business_for_sale"],
        [376, "blips/radar_race_bike.png", "radar_race_bike"],
        [377, "blips/radar_parachute.png", "radar_parachute"],
        [378, "blips/radar_team_deathmatch.png", "radar_team_deathmatch"],
        [379, "blips/radar_race_foot.png", "radar_race_foot"],
        [380, "blips/radar_vehicle_deathmatch.png", "radar_vehicle_deathmatch"],
        [381, "blips/radar_barry.png", "radar_barry"],
        [382, "blips/radar_dom.png", "radar_dom"],
        [383, "blips/radar_maryann.png", "radar_maryann"],
        [384, "blips/radar_cletus.png", "radar_cletus"],
        [385, "blips/radar_josh.png", "radar_josh"],
        [386, "blips/radar_minute.png", "radar_minute"],
        [387, "blips/radar_omega.png", "radar_omega"],
        [388, "blips/radar_tonya.png", "radar_tonya"],
        [389, "blips/radar_paparazzo.png", "radar_paparazzo"],
        [390, "blips/radar_aim.png", "radar_aim"],
        [391, "blips/radar_cratedrop_background.png", "radar_cratedrop_background"],
        [392, "blips/radar_green_and_net_player1.png", "radar_green_and_net_player1"],
        [393, "blips/radar_green_and_net_player2.png", "radar_green_and_net_player2"],
        [394, "blips/radar_green_and_net_player3.png", "radar_green_and_net_player3"],
        [395, "blips/radar_green_and_friendly.png", "radar_green_and_friendly"],
        [396, "blips/radar_net_player1_and_net_player2.png", "radar_net_player1_and_net_player2"],
        [397, "blips/radar_net_player1_and_net_player3.png", "radar_net_player1_and_net_player3"],
        [398, "blips/radar_creator.png", "radar_creator"],
        [399, "blips/radar_creator_direction.png", "radar_creator_direction"],
        [400, "blips/radar_abigail.png", "radar_abigail"],
        [401, "blips/radar_blimp.png", "radar_blimp"],
        [402, "blips/radar_repair.png", "radar_repair"],
        [403, "blips/radar_testosterone.png", "radar_testosterone"],
        [404, "blips/radar_dinghy.png", "radar_dinghy"],
        [405, "blips/radar_fanatic.png", "radar_fanatic"],
        [407, "blips/radar_info_icon.png", "radar_info_icon"],
        [408, "blips/radar_capture_the_flag.png", "radar_capture_the_flag"],
        [409, "blips/radar_last_team_standing.png", "radar_last_team_standing"],
        [410, "blips/radar_boat.png", "radar_boat"],
        [411, "blips/radar_capture_the_flag_base.png", "radar_capture_the_flag_base"],
        // [412, "blips/radar_mp_crew.png", "radar_mp_crew"],
        [413, "blips/radar_capture_the_flag_outline.png", "radar_capture_the_flag_outline"],
        // [414, "blips/radar_capture_the_flag_base_nobag.png", "radar_capture_the_flag_base_nobag"],
        [415, "blips/radar_weapon_jerrycan.png", "radar_weapon_jerrycan"],
        [416, "blips/radar_rp.png", "radar_rp"],
        [417, "blips/radar_level_inside.png", "radar_level_inside"],
        [418, "blips/radar_bounty_hit_inside.png", "radar_bounty_hit_inside"],
        [419, "blips/radar_capture_the_usaflag.png", "radar_capture_the_usaflag"],
        [420, "blips/radar_capture_the_usaflag_outline.png", "radar_capture_the_usaflag_outline"],
        [421, "blips/radar_tank.png", "radar_tank"],
        [422, "blips/radar_player_heli.png", "radar_player_heli"],
        [423, "blips/radar_player_plane.png", "radar_player_plane"],
        [424, "blips/radar_player_jet.png", "radar_player_jet"],
        // [425, "blips/radar_centre_stroke.png", "radar_centre_stroke"],
        [426, "blips/radar_player_guncar.png", "radar_player_guncar"],
        [427, "blips/radar_player_boat.png", "radar_player_boat"],
        [428, "blips/radar_mp_heist.png", "radar_mp_heist"],
        [429, "blips/radar_temp_1.png", "radar_temp_1"],
        [430, "blips/radar_temp_2.png", "radar_temp_2"],
        [431, "blips/radar_temp_3.png", "radar_temp_3"],
        [432, "blips/radar_temp_4.png", "radar_temp_4"],
        [433, "blips/radar_temp_5.png", "radar_temp_5"],
        [434, "blips/radar_temp_6.png", "radar_temp_6"],
        [435, "blips/radar_race_stunt.png", "radar_race_stunt"],
        [436, "blips/radar_hot_property.png", "radar_hot_property"],
        [437, "blips/radar_urbanwarfare_versus.png", "radar_urbanwarfare_versus"],
        [438, "blips/radar_king_of_the_castle.png", "radar_king_of_the_castle"],
        [439, "blips/radar_player_king.png", "radar_player_king"],
        [440, "blips/radar_dead_drop.png", "radar_dead_drop"],
        [441, "blips/radar_penned_in.png", "radar_penned_in"],
        [442, "blips/radar_beast.png", "radar_beast"],
        [443, "blips/radar_edge_pointer.png", "radar_edge_pointer"],
        [444, "blips/radar_edge_crosstheline.png", "radar_edge_crosstheline"],
        [445, "blips/radar_mp_lamar.png", "radar_mp_lamar"],
        [446, "blips/radar_bennys.png", "radar_bennys"],
        [447, "blips/radar_corner_number_1.png", "radar_corner_number_1"],
        [448, "blips/radar_corner_number_2.png", "radar_corner_number_2"],
        [449, "blips/radar_corner_number_3.png", "radar_corner_number_3"],
        [450, "blips/radar_corner_number_4.png", "radar_corner_number_4"],
        [451, "blips/radar_corner_number_5.png", "radar_corner_number_5"],
        [452, "blips/radar_corner_number_6.png", "radar_corner_number_6"],
        [453, "blips/radar_corner_number_7.png", "radar_corner_number_7"],
        [454, "blips/radar_corner_number_8.png", "radar_corner_number_8"],
        [455, "blips/radar_yacht.png", "radar_yacht"],
        [456, "blips/radar_finders_keepers.png", "radar_finders_keepers"],
        [457, "blips/radar_assault_package.png", "radar_assault_package"],
        [458, "blips/radar_hunt_the_boss.png", "radar_hunt_the_boss"],
        [459, "blips/radar_sightseer.png", "radar_sightseer"],
        [460, "blips/radar_turreted_limo.png", "radar_turreted_limo"],
        [461, "blips/radar_belly_of_the_beast.png", "radar_belly_of_the_beast"],
        [462, "blips/radar_yacht_location.png", "radar_yacht_location"],
        [463, "blips/radar_pickup_beast.png", "radar_pickup_beast"],
        [464, "blips/radar_pickup_zoned.png", "radar_pickup_zoned"],
        [465, "blips/radar_pickup_random.png", "radar_pickup_random"],
        [466, "blips/radar_pickup_slow_time.png", "radar_pickup_slow_time"],
        [467, "blips/radar_pickup_swap.png", "radar_pickup_swap"],
        [468, "blips/radar_pickup_thermal.png", "radar_pickup_thermal"],
        [469, "blips/radar_pickup_weed.png", "radar_pickup_weed"],
        [470, "blips/radar_weapon_railgun.png", "radar_weapon_railgun"],
        [471, "blips/radar_seashark.png", "radar_seashark"],
        [472, "blips/radar_pickup_hidden.png", "radar_pickup_hidden"],
        [473, "blips/radar_warehouse.png", "radar_warehouse"],
        [474, "blips/radar_warehouse_for_sale.png", "radar_warehouse_for_sale"],
        [475, "blips/radar_office.png", "radar_office"],
        [476, "blips/radar_office_for_sale.png", "radar_office_for_sale"],
        [477, "blips/radar_truck.png", "radar_truck"],
        [478, "blips/radar_contraband.png", "radar_contraband"],
        [479, "blips/radar_trailer.png", "radar_trailer"],
        [480, "blips/radar_vip.png", "radar_vip"],
        [481, "blips/radar_cargobob.png", "radar_cargobob"],
        // [482, "blips/radar_area_outline_blip.png", "radar_area_outline_blip"],
        [483, "blips/radar_pickup_accelerator.png", "radar_pickup_accelerator"],
        [484, "blips/radar_pickup_ghost.png", "radar_pickup_ghost"],
        [485, "blips/radar_pickup_detonator.png", "radar_pickup_detonator"],
        [486, "blips/radar_pickup_bomb.png", "radar_pickup_bomb"],
        [487, "blips/radar_pickup_armoured.png", "radar_pickup_armoured"],
        [488, "blips/radar_stunt.png", "radar_stunt"],
        [489, "blips/radar_weapon_lives.png", "radar_weapon_lives"],
        [490, "blips/radar_stunt_premium.png", "radar_stunt_premium"],
        [491, "blips/radar_adversary.png", "radar_adversary"],
        [492, "blips/radar_biker_clubhouse.png", "radar_biker_clubhouse"],
        [493, "blips/radar_biker_caged_in.png", "radar_biker_caged_in"],
        [494, "blips/radar_biker_turf_war.png", "radar_biker_turf_war"],
        [495, "blips/radar_biker_joust.png", "radar_biker_joust"],
        [496, "blips/radar_production_weed.png", "radar_production_weed"],
        [497, "blips/radar_production_crack.png", "radar_production_crack"],
        [498, "blips/radar_production_fake_id.png", "radar_production_fake_id"],
        [499, "blips/radar_production_meth.png", "radar_production_meth"],
        [500, "blips/radar_production_money.png", "radar_production_money"],
        [501, "blips/radar_package.png", "radar_package"],
        [502, "blips/radar_capture_1.png", "radar_capture_1"],
        [503, "blips/radar_capture_2.png", "radar_capture_2"],
        [504, "blips/radar_capture_3.png", "radar_capture_3"],
        [505, "blips/radar_capture_4.png", "radar_capture_4"],
        [506, "blips/radar_capture_5.png", "radar_capture_5"],
        [507, "blips/radar_capture_6.png", "radar_capture_6"],
        [508, "blips/radar_capture_7.png", "radar_capture_7"],
        [509, "blips/radar_capture_8.png", "radar_capture_8"],
        [510, "blips/radar_capture_9.png", "radar_capture_9"],
        [511, "blips/radar_capture_10.png", "radar_capture_10"],
        [512, "blips/radar_quad.png", "radar_quad"],
        [513, "blips/radar_bus.png", "radar_bus"],
        [514, "blips/radar_drugs_package.png", "radar_drugs_package"],
        [515, "blips/radar_pickup_jump.png", "radar_pickup_jump"],
        [516, "blips/radar_adversary_4.png", "radar_adversary_4"],
        [517, "blips/radar_adversary_8.png", "radar_adversary_8"],
        [518, "blips/radar_adversary_10.png", "radar_adversary_10"],
        [519, "blips/radar_adversary_12.png", "radar_adversary_12"],
        [520, "blips/radar_adversary_16.png", "radar_adversary_16"],
        [521, "blips/radar_laptop.png", "radar_laptop"],
        [522, "blips/radar_pickup_deadline.png", "radar_pickup_deadline"],
        [523, "blips/radar_sports_car.png", "radar_sports_car"],
        [524, "blips/radar_warehouse_vehicle.png", "radar_warehouse_vehicle"],
        [525, "blips/radar_reg_papers.png", "radar_reg_papers"],
        [526, "blips/radar_police_station_dropoff.png", "radar_police_station_dropoff"],
        [527, "blips/radar_junkyard.png", "radar_junkyard"],
        [528, "blips/radar_ex_vech_1.png", "radar_ex_vech_1"],
        [529, "blips/radar_ex_vech_2.png", "radar_ex_vech_2"],
        [530, "blips/radar_ex_vech_3.png", "radar_ex_vech_3"],
        [531, "blips/radar_ex_vech_4.png", "radar_ex_vech_4"],
        [532, "blips/radar_ex_vech_5.png", "radar_ex_vech_5"],
        [533, "blips/radar_ex_vech_6.png", "radar_ex_vech_6"],
        [534, "blips/radar_ex_vech_7.png", "radar_ex_vech_7"],
        [535, "blips/radar_target_a.png", "radar_target_a"],
        [536, "blips/radar_target_b.png", "radar_target_b"],
        [537, "blips/radar_target_c.png", "radar_target_c"],
        [538, "blips/radar_target_d.png", "radar_target_d"],
        [539, "blips/radar_target_e.png", "radar_target_e"],
        [540, "blips/radar_target_f.png", "radar_target_f"],
        [541, "blips/radar_target_g.png", "radar_target_g"],
        [542, "blips/radar_target_h.png", "radar_target_h"],
        [543, "blips/radar_jugg.png", "radar_jugg"],
        [544, "blips/radar_pickup_repair.png", "radar_pickup_repair"],
        [545, "blips/radar_steeringwheel.png", "radar_steeringwheel"],
        [546, "blips/radar_trophy.png", "radar_trophy"],
        [547, "blips/radar_pickup_rocket_boost.png", "radar_pickup_rocket_boost"],
        [548, "blips/radar_pickup_homing_rocket.png", "radar_pickup_homing_rocket"],
        [549, "blips/radar_pickup_machinegun.png", "radar_pickup_machinegun"],
        [550, "blips/radar_pickup_parachute.png", "radar_pickup_parachute"],
        [551, "blips/radar_pickup_time_5.png", "radar_pickup_time_5"],
        [552, "blips/radar_pickup_time_10.png", "radar_pickup_time_10"],
        [553, "blips/radar_pickup_time_15.png", "radar_pickup_time_15"],
        [554, "blips/radar_pickup_time_20.png", "radar_pickup_time_20"],
        [555, "blips/radar_pickup_time_30.png", "radar_pickup_time_30"],
        [556, "blips/radar_supplies.png", "radar_supplies"],
        [557, "blips/radar_property_bunker.png", "radar_property_bunker"],
        [558, "blips/radar_gr_wvm_1.png", "radar_gr_wvm_1"],
        [559, "blips/radar_gr_wvm_2.png", "radar_gr_wvm_2"],
        [560, "blips/radar_gr_wvm_3.png", "radar_gr_wvm_3"],
        [561, "blips/radar_gr_wvm_4.png", "radar_gr_wvm_4"],
        [562, "blips/radar_gr_wvm_5.png", "radar_gr_wvm_5"],
        [563, "blips/radar_gr_wvm_6.png", "radar_gr_wvm_6"],
        [564, "blips/radar_gr_covert_ops.png", "radar_gr_covert_ops"],
        [565, "blips/radar_adversary_bunker.png", "radar_adversary_bunker"],
        [566, "blips/radar_gr_moc_upgrade.png", "radar_gr_moc_upgrade"],
        [567, "blips/radar_gr_w_upgrade.png", "radar_gr_w_upgrade"],
        [568, "blips/radar_sm_cargo.png", "radar_sm_cargo"],
        [569, "blips/radar_sm_hangar.png", "radar_sm_hangar"],
        [570, "blips/radar_tf_checkpoint.png", "radar_tf_checkpoint"],
        [571, "blips/radar_race_tf.png", "radar_race_tf"],
        [572, "blips/radar_sm_wp1.png", "radar_sm_wp1"],
        [573, "blips/radar_sm_wp2.png", "radar_sm_wp2"],
        [574, "blips/radar_sm_wp3.png", "radar_sm_wp3"],
        [575, "blips/radar_sm_wp4.png", "radar_sm_wp4"],
        [576, "blips/radar_sm_wp5.png", "radar_sm_wp5"],
        [577, "blips/radar_sm_wp6.png", "radar_sm_wp6"],
        [578, "blips/radar_sm_wp7.png", "radar_sm_wp7"],
        [579, "blips/radar_sm_wp8.png", "radar_sm_wp8"],
        [580, "blips/radar_sm_wp9.png", "radar_sm_wp9"],
        [581, "blips/radar_sm_wp10.png", "radar_sm_wp10"],
        [582, "blips/radar_sm_wp11.png", "radar_sm_wp11"],
        [583, "blips/radar_sm_wp12.png", "radar_sm_wp12"],
        [584, "blips/radar_sm_wp13.png", "radar_sm_wp13"],
        [585, "blips/radar_sm_wp14.png", "radar_sm_wp14"],
        [586, "blips/radar_nhp_bag.png", "radar_nhp_bag"],
        [587, "blips/radar_nhp_chest.png", "radar_nhp_chest"],
        [588, "blips/radar_nhp_orbit.png", "radar_nhp_orbit"],
        [589, "blips/radar_nhp_veh1.png", "radar_nhp_veh1"],
        [590, "blips/radar_nhp_base.png", "radar_nhp_base"],
        [591, "blips/radar_nhp_overlay.png", "radar_nhp_overlay"],
        [592, "blips/radar_nhp_turret.png", "radar_nhp_turret"],
        [593, "blips/radar_nhp_mg_firewall.png", "radar_nhp_mg_firewall"],
        [594, "blips/radar_nhp_mg_node.png", "radar_nhp_mg_node"],
        [595, "blips/radar_nhp_wp1.png", "radar_nhp_wp1"],
        [596, "blips/radar_nhp_wp2.png", "radar_nhp_wp2"],
        [597, "blips/radar_nhp_wp3.png", "radar_nhp_wp3"],
        [598, "blips/radar_nhp_wp4.png", "radar_nhp_wp4"],
        [599, "blips/radar_nhp_wp5.png", "radar_nhp_wp5"],
        [600, "blips/radar_nhp_wp6.png", "radar_nhp_wp6"],
        [601, "blips/radar_nhp_wp7.png", "radar_nhp_wp7"],
        [602, "blips/radar_nhp_wp8.png", "radar_nhp_wp8"],
        [603, "blips/radar_nhp_wp9.png", "radar_nhp_wp9"],
        [604, "blips/radar_nhp_cctv.png", "radar_nhp_cctv"],
        [605, "blips/radar_nhp_starterpack.png", "radar_nhp_starterpack"],
        [606, "blips/radar_nhp_turret_console.png", "radar_nhp_turret_console"],
        [607, "blips/radar_nhp_mg_mir_rotate.png", "radar_nhp_mg_mir_rotate"],
        [608, "blips/radar_nhp_mg_mir_static.png", "radar_nhp_mg_mir_static"],
        [609, "blips/radar_nhp_mg_proxy.png", "radar_nhp_mg_proxy"],
        [610, "blips/radar_acsr_race_target.png", "radar_acsr_race_target"],
        [611, "blips/radar_acsr_race_hotring.png", "radar_acsr_race_hotring"],
        [612, "blips/radar_acsr_wp1.png", "radar_acsr_wp1"],
        [613, "blips/radar_acsr_wp2.png", "radar_acsr_wp2"],
        [614, "blips/radar_bat_club_property.png", "radar_bat_club_property"],
        [615, "blips/radar_bat_cargo.png", "radar_bat_cargo"],
        [616, "blips/radar_bat_truck.png", "radar_bat_truck"],
        [617, "blips/radar_bat_hack_jewel.png", "radar_bat_hack_jewel"],
        [618, "blips/radar_bat_hack_gold.png", "radar_bat_hack_gold"],
        [619, "blips/radar_bat_keypad.png", "radar_bat_keypad"],
        [620, "blips/radar_bat_hack_target.png", "radar_bat_hack_target"],
        [621, "blips/radar_pickup_dtb_health.png", "radar_pickup_dtb_health"],
        [622, "blips/radar_pickup_dtb_blast_increase.png", "radar_pickup_dtb_blast_increase"],
        [623, "blips/radar_pickup_dtb_blast_decrease.png", "radar_pickup_dtb_blast_decrease"],
        [624, "blips/radar_pickup_dtb_bomb_increase.png", "radar_pickup_dtb_bomb_increase"],
        [625, "blips/radar_pickup_dtb_bomb_decrease.png", "radar_pickup_dtb_bomb_decrease"],
        [626, "blips/radar_bat_rival_club.png", "radar_bat_rival_club"],
        [627, "blips/radar_bat_drone.png", "radar_bat_drone"],
        [628, "blips/radar_bat_cash_reg.png", "radar_bat_cash_reg"],
        [629, "blips/radar_cctv.png", "radar_cctv"],
        [630, "blips/radar_bat_assassinate.png", "radar_bat_assassinate"],
        [631, "blips/radar_bat_pbus.png", "radar_bat_pbus"],
        [632, "blips/radar_bat_wp1.png", "radar_bat_wp1"],
        [633, "blips/radar_bat_wp2.png", "radar_bat_wp2"],
        [634, "blips/radar_bat_wp3.png", "radar_bat_wp3"],
        [635, "blips/radar_bat_wp4.png", "radar_bat_wp4"],
        [636, "blips/radar_bat_wp5.png", "radar_bat_wp5"],
        [637, "blips/radar_bat_wp6.png", "radar_bat_wp6"],
        [638, "blips/radar_blimp_2.png", "radar_blimp_2"],
        [639, "blips/radar_oppressor_2.png", "radar_oppressor_2"],
        [640, "blips/radar_bat_wp7.png", "radar_bat_wp7"],
        [641, "blips/radar_arena_series.png", "radar_arena_series"],
        [642, "blips/radar_arena_premium.png", "radar_arena_premium"],
        [643, "blips/radar_arena_workshop.png", "radar_arena_workshop"],
        [644, "blips/radar_race_wars.png", "radar_race_wars"],
        [645, "blips/radar_arena_turret.png", "radar_arena_turret"],
        [646, "blips/radar_arena_rc_car.png", "radar_arena_rc_car"],
        [647, "blips/radar_arena_rc_workshop.png", "radar_arena_rc_workshop"],
        [648, "blips/radar_arena_trap_fire.png", "radar_arena_trap_fire"],
        [649, "blips/radar_arena_trap_flip.png", "radar_arena_trap_flip"],
        [650, "blips/radar_arena_trap_sea.png", "radar_arena_trap_sea"],
        [651, "blips/radar_arena_trap_turn.png", "radar_arena_trap_turn"],
        [652, "blips/radar_arena_trap_pit.png", "radar_arena_trap_pit"],
        [653, "blips/radar_arena_trap_mine.png", "radar_arena_trap_mine"],
        [654, "blips/radar_arena_trap_bomb.png", "radar_arena_trap_bomb"],
        [655, "blips/radar_arena_trap_wall.png", "radar_arena_trap_wall"],
        [656, "blips/radar_arena_trap_brd.png", "radar_arena_trap_brd"],
        [657, "blips/radar_arena_trap_sbrd.png", "radar_arena_trap_sbrd"],
        [658, "blips/radar_arena_bruiser.png", "radar_arena_bruiser"],
        [659, "blips/radar_arena_brutus.png", "radar_arena_brutus"],
        [660, "blips/radar_arena_cerberus.png", "radar_arena_cerberus"],
        [661, "blips/radar_arena_deathbike.png", "radar_arena_deathbike"],
        [662, "blips/radar_arena_dominator.png", "radar_arena_dominator"],
        [663, "blips/radar_arena_impaler.png", "radar_arena_impaler"],
        [664, "blips/radar_arena_imperator.png", "radar_arena_imperator"],
        [665, "blips/radar_arena_issi.png", "radar_arena_issi"],
        [666, "blips/radar_arena_sasquatch.png", "radar_arena_sasquatch"],
        [667, "blips/radar_arena_scarab.png", "radar_arena_scarab"],
        [668, "blips/radar_arena_slamvan.png", "radar_arena_slamvan"],
        [669, "blips/radar_arena_zr380.png", "radar_arena_zr380"],
    ]
}
